spring.application.name=event-handler-service

spring.output.ansi.enabled=always

spring.datasource.url=jdbc:postgresql://localhost:5432/cargo_tracking_sys_db
spring.datasource.username=cts_user
spring.datasource.password=ctsDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=shipment-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record